### ISSUE TITLE
Feature - Suggestbox dropdown when clicked with no characters

### ISSUE THREAD

**Issue by prospectoria** [salk31/RedQueryBuilder#26]
The gwt-Suggestbox needs to make it's ajax call for it's list of values when clicked and no characters are entered.  Currently you must type a character before the ajax call is made, then it populates the dropdown.  We need this to be modified so that it makes the call for a list of values when the box is clicked, regardless of whether they have typed a character or not.

**Comment by Ratnesh-Github** [comment]
I also need this feature in my app. If a user comes to an input field, suggestion box should show options without them requiring to type. And when they types any letter, it should filter the options based on the letter.

**Comment by salk31** [comment]
Please could you test this:
https://0-8-0-dot-redquerybuilder.appspot.com/
?  Silly default to things starting with "e"

**Comment by Ratnesh-Github** [comment]
Yeah it is showing all the options. But it is defaulting to "e" right now. Thanks !.  It might be useful if there is a scroll bar too on the suggestion list. Right now it is difficult to see the options at the end of suggestion list.
