### ISSUE TITLE
How to implement the suggestion box ? I am facing difficulties in implementing suggestion box. Can we elaborate more on it in docs ?

### ISSUE THREAD

**Issue by Ratnesh-Github** [salk31/RedQueryBuilder#41]

**Comment by salk31** [comment]
Definitely. What problem are you having? Be great if you could create a commit to improve the docs.

**Comment by salk31** [comment]
Did you see the source from the live example:
https://github.com/salk31/RedQueryBuilder/blob/master/redquerybuilder-jdbcsample/src/main/webapp/index.html#L221

**Comment by Ratnesh-Github** [comment]
I am sorry I missed that. I think that should be enough for me. I will close this issue. And while we are at it, I need a feature where we can show the suggestion box without user typing anything in the box. I can see there is a enhancement request for it already. Thanks for the quick response. It is a great tool.

**Comment by salk31** [comment]
Great. In that case please could you close that ticket and comment on the other one to say you want that feature too? It would be great if you could describe your use case.
